In [38]:
#Problem_1
import numpy as np

# Array: An array is a vector containing homogeneous elements i.e. belonging to the same data type. Elements are allocated with 
# contiguous memory locations. Typically the size of an array is fixed. Insertion and Deletion costs high as compare to List however 
# indexing is fast in the Arrays due to contiguous memory allocation.

list_ = [ '1' , '2',  '3' , '4' , '5' ]
array_list = np.array(list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [42]:
# List: A list in Python is a collection of items which can contain elements of multiple data types, which may be either numeric, 
# character logical values, etc. It is an ordered collection supporting negative indexing. A list can be created using [] containing
# data values. Contents of lists can be easily merged and copied using python’s inbuilt functions. 
list_= [ '1' , '2',  '3' , '4' , '5' ]
print(list_)


['1', '2', '3', '4', '5']


In [27]:
#Problem_2

list_ = [ '1' , '2',  '3' , '4' , '5' ]
np.array(list_)
list_
type(list_)


list

In [53]:
sample_list = [ '1' , '2',  '3' , '4' , '5' ]
print(sample_list)
type(sample_list)


['1', '2', '3', '4', '5']


list

In [32]:
#Problem_3
list_ = [ '1' , '2',  '3' , '4' , '5' ]
array_list = np.array(list_)
list2 = array_list.astype(np.int64)
list2.dtype

dtype('int64')

In [45]:


list_ = [ '1' , '2',  '3' , '4' , '5' ]
for i in list_:
    print(type(i))

type(list_)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


list

In [48]:
#Problem_4
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
num_array.shape

(2, 3)

In [50]:
num_array.size

6

In [57]:
#Problem_5
matrix = np.zeros((3,3))
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
matrix.shape

(3, 3)

In [59]:
matrix.size

9

In [62]:
#Problem_6
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])